# docker-compose.linux.yml
version: '3.8'

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: openvulnscan-zap
    command: >
      zap.sh -daemon -port 8080 -host 0.0.0.0 
      -config api.disablekey=true 
      -config api.addrs.addr.name=.* 
      -config api.addrs.addr.regex=true 
      -config connection.timeoutInSecs=600
      -config network.localhost.proxy.excludeRegex=true 
      -config network.general.dnsTtlSuccessfulQueries=-1
    volumes:
      - zap_results:/zap/wrk
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    environment:
      - JAVA_OPTS="-Xmx4g"
      - ZAP_DOCKER_ALLOW_HOST=true
    network_mode: host
    ports: []        # Prevents trying to bind ports with host mode

volumes:
  zap_results:
